### PR TITLE
Update comm.network

### PR DESCRIPTION
**Pull request by lfuelling**
Hi,

thanks for putting my instance on that list. 

I've updated the rules screenshot because it was outdated and added some comments because the initial assumptions about this instance are wrong.

I know how hard it is for people like those maintaining lists like this to let the bad, bad people that are on it defend themselves against false accusations so if you must, feel free to remove my straight up lies!

Regards and have a nice day

Lukas

### CODE REVIEW

**Comment by nicolaisueper** [comment]
I also think @dzuk-mutant is very biased.

Just because @lfuelling confronted another person with his opinion, this does not make his post 'shitty' or 'abusive'. I don't see any swearing or offending words in this case.

Maybe you should put the whole Fediverse onto your blocklist, shouldn't you?

**Comment by lfuelling** [comment]
It's what feminists (the ones that confuse their definition of feminism with the already existing equalism) do. They use nazi methods and justify it with being against nazis/hate speech/whatever, even if there is none.

**Comment by lfuelling** [comment]
Oh in case you didn't know @nicolaisueper the above comment is also abusive, harrassing and nazi-like, because I accused the only good-doing listkeepers with something.

**Comment by nicolaisueper** [comment]
I wouldn't bother if comm.network stays on that list. Maybe it results in a less square timeline.

**Comment by lfuelling** [comment]
That's why I added information instead of removing it :)

**Comment by asonix** [comment]
I hadn't blocked y'all but the conversation you just had here is reason enough.

**Comment by lfuelling** [comment]
Do it 🙃

**Pull request closed without merging**
