### PR TITLE
Added more details re:qoto.

### PR DESCRIPTION
**Pull request by freemo**
Added more details about the qoto instance post.

### CODE REVIEW

**Comment by freemo** [comment]
@dzuk-mutant Is there going to be some movement on this at some point. I would assume you'd want the complete body of evidence posted no?

**Comment by freemo** [comment]
@dzuk-mutant its been 20 days since this PR was opened, no activity...

**Comment by freemo** [comment]
Now a month since the PR was submited with absolutely no response. 

Seems this block-chain has absolutely **no** accountability to the facts, its just one persons personal vendetta list?

@dzuk-mutant

**Comment by a-dows** [comment]
Let it go, dude.

**Comment by freemo** [comment]
@a-dows I'm trying to work with a group that tries to verify which block lists have accountability and what dont (a list of lists). So I wanted to do the due diligence to build up an evidence based-case against this particular list. a month with no response should be significant information to show publicly that this list does not have any sense of accountability.

**Comment by a-dows** [comment]
@freemo Have you tried reaching out to dzuk directly, rather than using a pull request?

**Comment by freemo** [comment]
@a-dows yup, also contacted him as a DM on mastodon, which is what he listed as his preferred way of communication.

**Comment by a-dows** [comment]
@freemo "Accountability" is not a tremendously measurable metric. I implement this list on my instance because I find the reasoning sound and the examples clear. If you disagree with the rationale behind an instance's inclusion on this list, don't block that instance. To be honest, I'm not sure what the use of your group's seal of approval would be.

**Comment by freemo** [comment]
@a-dows it will be a system that integrates other lists, we will only be including lists that are accountable, what that means is that only lists which give truthful and complete statements on the incidents which get someone on the list. Since this list is found to not be honest/complete it will most likely disqualify them from being int he library.

**Comment by dzuk-mutant** [comment]
@freemo I really don't appreciate the malicious presumptions on your part. I apologise for not mentioning it in this PR (I have social anxiety so I will put off responding to certain things for a long time) but I am currently on hiatus with anything to do with BLOCKchain until November. I have noticed your PR and intend on investigating and responding to it when I come back.

**Comment by freemo** [comment]
@dzuk-mutant no malicious presumptions intended, I hope you feel better soon, the best of luck to you.

**Comment by freemo** [comment]
@dzuk-mutant the committee is voting on how to classify this block list this friday. They will be considering this thread, as well as the mastodon messages I sent, to determine if this list meets the criteria (accountability and due diligence). If you have any last minute comments you'd like them to hear please feel free to post it here. I'll be sure they see any updates at the meeting, thanks.

**Comment by dzuk-mutant** [comment]
As promised, I looked at the file I had for this instance and I absolutely stand by my decision.

I thought all I had on this instance was that particular post, but then there's the rules which paints a very clear ideological picture. It's just as deserving as everything else here.

**Comment by freemo** [comment]
@dzuk-mutant What? This was NOT a request for you to reverse your decision. It was additional information about the exchange that was intentionally left out. Did you even review the PR? For the record this has gotten the QOTO server a LOT of new users, so the last thing we would want is to be take off the list. All we wanted was the evidence to be complete so people can make an informed decision.

**Pull request closed without merging**
