### PR TITLE
Add gasthe.lgbt

### PR DESCRIPTION
**Pull request by rummik**
Apparently run by the gameliberty. club admin

### CODE REVIEW

**Comment by dzuk-mutant** [comment]
Thanks! Do you mind if I add a little bit just saying sth like 'this should be obvious why you'd want to add this because fo the domain' and add the archived conversation from the admin about getting the domain?

**Comment by dzuk-mutant** [comment]
Oh also, would you like me to specifically credit you in the post or in the readme for contributing? I'd figured it's best to ask because not everyone would understandably want to do that.

**Comment by dzuk-mutant** [comment]
I've added my own version of the file just to get this done while I had the spoons (and because I wanted to tie it in with 2 other instances on the list), but let me know about the credits!!! (and sorry for stepping over like that >.<, I really appreciate your contribution!)

**Comment by rummik** [comment]
@dzuk-mutant Credit and modifications are totally fine! 😅 (I'd have responded sooner, but I've been on an emergency trip the past week, and haven't had the chance to check my notifications)

**Pull request closed without merging**
